name: Deploy Data Lake Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: BigDataTerraform/terraform/envs/dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # AWS Auth
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # PYTHON
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # DEPENDENCIAS
      - name: Install dependencies
        run: |
          pip install pytest pyspark
      
      # Set PYTHONPATH para que los tests encuentren los scripts
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE/BigDataTerraform/terraform/archivos_para_bronze" >> $GITHUB_ENV

      # RUN TESTS
      - name: Run Tests
        run: |
          python -m pytest $GITHUB_WORKSPACE/BigDataTerraform/terraform/archivos_para_bronze/tests/

      # Terraform Setup
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_wrapper: false

      # Inicialización con -upgrade para evitar conflictos de versiones
      - name: Terraform Init
        run: terraform init -upgrade

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -var-file="dev.tfvars"

      - name: Terraform Apply
        run: terraform apply -auto-approve -var-file="dev.tfvars"

      # Capturar bucket para scripts
      - name: Get Terraform Outputs
        run: |
            BUCKET=$(terraform output -raw raw_bucket_name)
            echo "BRONZE_BUCKET=$BUCKET" >> $GITHUB_ENV

      # Subir datos crudos
      - name: Upload JSON
        run: |
          aws s3 cp $GITHUB_WORKSPACE/BigDataTerraform/terraform/archivos_para_bronze/Datos_SIATA_Aire_pm25_reducido.json s3://$BRONZE_BUCKET/

      # Subir los 3 scripts de la arquitectura Medallion
      - name: Upload Glue Scripts
        run: |
          aws s3 cp $GITHUB_WORKSPACE/BigDataTerraform/terraform/archivos_para_bronze/scripts/validate_expectations.py s3://$BRONZE_BUCKET/scripts/
          aws s3 cp $GITHUB_WORKSPACE/BigDataTerraform/terraform/archivos_para_bronze/scripts/bronze_to_silver.py s3://$BRONZE_BUCKET/scripts/
          aws s3 cp $GITHUB_WORKSPACE/BigDataTerraform/terraform/archivos_para_bronze/scripts/silver_to_gold.py s3://$BRONZE_BUCKET/scripts/